### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hugotrassoudaine** [hugotrassoudaine/projet-javaee#1]
- [ ] Système de recherche
  - [ ] Lister les catégories quand il n'y a pas de paramètres sur une requete /search
  - [ ] Lister les articles dans une catégorie si le paramètre `c` est présent
  - [ ] Lister les articles pertinents si le paramètre `s` est présent
- [ ] Visualisation des détails d'un article
  - [ ] /view_product?p=PRODUCT_ID
  - [ ] /view_product sans paramètres redirige vers la page d'accueil car `Bad Request`
- [ ] Validation du panier
- [ ] Page de visualisation des stats admin
  - [x] /admin
  - [ ] Navigation avec des onglets (soit bootstrap `tab`, soit autre, à voir)
  - [ ] Page édition de la table Produit (barre de recherche d'un produit -> afficher un formulaire du produit
  - [ ] Page visualisation chiffre d'affaire par article
  - [ ] Page visualisation chiffre d'affaire par pays
  - [ ] Page visualisation chiffre d'affaire par client
